name: Build Container
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  api:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == 'api' }}
    steps:
      - uses: actions/checkout@v3

      - name: Echo
        run: echo "Building API"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push
        run: |
          docker-compose -f docker-compose.yml build --no-cache strapi
          docker push ghcr.io/Deft-Dodo-Web-Development/website:latest
